name: github actions

on:
  push:
    branches:
      - main
     
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: checkout branch "main"
        uses: actions/checkout@v2
